### ISSUE TITLE
`yaml` instead of `meta`?

### ISSUE THREAD

**Issue by wehrad** [cryo-data/cryo-data#3]
I was wondering what is the motivation behind the use of `meta` files instead of -what I consider as- more standard formats such as `json` or `yaml`?

`json` is very simple and low level but can't include direct comments (still possible by adding an extra field but this is just a trick), `yaml` is a bit higher level but gives a very clear structure and possible comments to the user.

For the [Polar EO database](https://github.com/APECS-Earth-Observation/Polar-EO-Database) our working group at APECS is currently working on, meant to list and describe the satellites and sensors used in the polar regions and associated info, we decided to go for `yaml`. Mainly because we want anyone to be able to contribute, see a simple example of template [here](https://github.com/APECS-Earth-Observation/Polar-EO-Database/blob/main/src/database_template.yaml) (WIP).

I just think `json` and `yaml` are used almost everywhere, so why not using it.

**Comment by mankoff** [comment]
Will do. 

Useful: https://stackoverflow.com/questions/5014632/how-can-i-parse-a-yaml-file-from-a-linux-shell-script

**Comment by wehrad** [comment]
Also maybe: https://github.com/mrbaseman/parse_yaml

**Comment by wehrad** [comment]
Love the bibtex entry in a yaml! :+1:
